---
stannis:
  uri: http://localhost:3000
  username: admin
  password: admin
deployments:
- bosh_really_uuid: 10.10.10.11-uuid-aws-bosh-production
  deployment_name: cf-aws-prod
  cf:
    api: https://api.run.pivotal.io
    skip_ssl_validation: false
    username: admin
    password: admin
- bosh_really_uuid: 10.10.10.11-uuid-aws-bosh-production
  deployment_name: cf-redis
  cf:
    api: https://api.10.244.0.34.xip.io
    skip_ssl_validation: false
    username: admin
    password: admin
  service_broker:
    url: http://cf-redis.10.244.0.34.xip.io
    username: broker
    password: broker
