#!/usr/bin/env ruby

require "aws_rds_snapshot_stannisplugin"
require "optparse"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: aws_rds_snapshot_stannisplugin [options]"

  opts.on("--version", "Show version") do |v|
    puts "aws_rds_snapshot_stannisplugin #{Stannis::Plugin::AwsRdsSnapshot::VERSION}"
    exit 0
  end
end.parse!

p options
p ARGV
