#!/usr/bin/env ruby

require "aws_rds_snapshot_stannisplugin"
require "optparse"

options = {}
opts = OptionParser.new do |opts|
  opts.banner = "Usage: aws_rds_snapshot_stannisplugin [options]"

  opts.on("-c", "--config CONFIG", "Path to configuration file") do |c|
    options[:config] = c
  end

  opts.separator ""
  opts.separator "Common options:"
  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
  opts.on("--version", "Show version") do |v|
    puts "aws_rds_snapshot_stannisplugin #{Stannis::Plugin::AwsRdsSnapshot::VERSION}"
    exit 0
  end
end

opts.parse!(ARGV)
unless options[:config]
  puts opts
  exit 1
end

config = Stannis::Plugin::AwsRdsSnapshot::Config.load_file(options[:config])
p config.fog_rds
